<?php

declare(strict_types=1);

namespace Increase\Files\File;

/**
 * Whether the File was generated by Increase or by you and sent to Increase.
 */
enum Direction: string
{
    case TO_INCREASE = 'to_increase';

    case FROM_INCREASE = 'from_increase';
}
