<?php

declare(strict_types=1);

namespace Increase\Simulations\CardBalanceInquiries;

use Increase\Core\Attributes\Optional;
use Increase\Core\Concerns\SdkModel;
use Increase\Core\Concerns\SdkParams;
use Increase\Core\Contracts\BaseModel;
use Increase\Simulations\CardBalanceInquiries\CardBalanceInquiryCreateParams\DeclineReason;
use Increase\Simulations\CardBalanceInquiries\CardBalanceInquiryCreateParams\NetworkDetails;

/**
 * Simulates a balance inquiry on a [Card](#cards).
 *
 * @see Increase\Services\Simulations\CardBalanceInquiriesService::create()
 *
 * @phpstan-import-type NetworkDetailsShape from \Increase\Simulations\CardBalanceInquiries\CardBalanceInquiryCreateParams\NetworkDetails
 *
 * @phpstan-type CardBalanceInquiryCreateParamsShape = array{
 *   balance?: int|null,
 *   cardID?: string|null,
 *   declineReason?: null|DeclineReason|value-of<DeclineReason>,
 *   digitalWalletTokenID?: string|null,
 *   eventSubscriptionID?: string|null,
 *   merchantAcceptorID?: string|null,
 *   merchantCategoryCode?: string|null,
 *   merchantCity?: string|null,
 *   merchantCountry?: string|null,
 *   merchantDescriptor?: string|null,
 *   merchantState?: string|null,
 *   networkDetails?: null|NetworkDetails|NetworkDetailsShape,
 *   networkRiskScore?: int|null,
 *   physicalCardID?: string|null,
 *   terminalID?: string|null,
 * }
 */
final class CardBalanceInquiryCreateParams implements BaseModel
{
    /** @use SdkModel<CardBalanceInquiryCreateParamsShape> */
    use SdkModel;
    use SdkParams;

    /**
     * The balance amount in cents. The account balance will be used if not provided.
     */
    #[Optional]
    public ?int $balance;

    /**
     * The identifier of the Card to be authorized.
     */
    #[Optional('card_id')]
    public ?string $cardID;

    /**
     * Forces a card decline with a specific reason. No real time decision will be sent.
     *
     * @var value-of<DeclineReason>|null $declineReason
     */
    #[Optional('decline_reason', enum: DeclineReason::class)]
    public ?string $declineReason;

    /**
     * The identifier of the Digital Wallet Token to be authorized.
     */
    #[Optional('digital_wallet_token_id')]
    public ?string $digitalWalletTokenID;

    /**
     * The identifier of the Event Subscription to use. If provided, will override the default real time event subscription. Because you can only create one real time decision event subscription, you can use this field to route events to any specified event subscription for testing purposes.
     */
    #[Optional('event_subscription_id')]
    public ?string $eventSubscriptionID;

    /**
     * The merchant identifier (commonly abbreviated as MID) of the merchant the card is transacting with.
     */
    #[Optional('merchant_acceptor_id')]
    public ?string $merchantAcceptorID;

    /**
     * The Merchant Category Code (commonly abbreviated as MCC) of the merchant the card is transacting with.
     */
    #[Optional('merchant_category_code')]
    public ?string $merchantCategoryCode;

    /**
     * The city the merchant resides in.
     */
    #[Optional('merchant_city')]
    public ?string $merchantCity;

    /**
     * The country the merchant resides in.
     */
    #[Optional('merchant_country')]
    public ?string $merchantCountry;

    /**
     * The merchant descriptor of the merchant the card is transacting with.
     */
    #[Optional('merchant_descriptor')]
    public ?string $merchantDescriptor;

    /**
     * The state the merchant resides in.
     */
    #[Optional('merchant_state')]
    public ?string $merchantState;

    /**
     * Fields specific to a given card network.
     */
    #[Optional('network_details')]
    public ?NetworkDetails $networkDetails;

    /**
     * The risk score generated by the card network. For Visa this is the Visa Advanced Authorization risk score, from 0 to 99, where 99 is the riskiest.
     */
    #[Optional('network_risk_score')]
    public ?int $networkRiskScore;

    /**
     * The identifier of the Physical Card to be authorized.
     */
    #[Optional('physical_card_id')]
    public ?string $physicalCardID;

    /**
     * The terminal identifier (commonly abbreviated as TID) of the terminal the card is transacting with.
     */
    #[Optional('terminal_id')]
    public ?string $terminalID;

    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param DeclineReason|value-of<DeclineReason>|null $declineReason
     * @param NetworkDetails|NetworkDetailsShape|null $networkDetails
     */
    public static function with(
        ?int $balance = null,
        ?string $cardID = null,
        DeclineReason|string|null $declineReason = null,
        ?string $digitalWalletTokenID = null,
        ?string $eventSubscriptionID = null,
        ?string $merchantAcceptorID = null,
        ?string $merchantCategoryCode = null,
        ?string $merchantCity = null,
        ?string $merchantCountry = null,
        ?string $merchantDescriptor = null,
        ?string $merchantState = null,
        NetworkDetails|array|null $networkDetails = null,
        ?int $networkRiskScore = null,
        ?string $physicalCardID = null,
        ?string $terminalID = null,
    ): self {
        $self = new self;

        null !== $balance && $self['balance'] = $balance;
        null !== $cardID && $self['cardID'] = $cardID;
        null !== $declineReason && $self['declineReason'] = $declineReason;
        null !== $digitalWalletTokenID && $self['digitalWalletTokenID'] = $digitalWalletTokenID;
        null !== $eventSubscriptionID && $self['eventSubscriptionID'] = $eventSubscriptionID;
        null !== $merchantAcceptorID && $self['merchantAcceptorID'] = $merchantAcceptorID;
        null !== $merchantCategoryCode && $self['merchantCategoryCode'] = $merchantCategoryCode;
        null !== $merchantCity && $self['merchantCity'] = $merchantCity;
        null !== $merchantCountry && $self['merchantCountry'] = $merchantCountry;
        null !== $merchantDescriptor && $self['merchantDescriptor'] = $merchantDescriptor;
        null !== $merchantState && $self['merchantState'] = $merchantState;
        null !== $networkDetails && $self['networkDetails'] = $networkDetails;
        null !== $networkRiskScore && $self['networkRiskScore'] = $networkRiskScore;
        null !== $physicalCardID && $self['physicalCardID'] = $physicalCardID;
        null !== $terminalID && $self['terminalID'] = $terminalID;

        return $self;
    }

    /**
     * The balance amount in cents. The account balance will be used if not provided.
     */
    public function withBalance(int $balance): self
    {
        $self = clone $this;
        $self['balance'] = $balance;

        return $self;
    }

    /**
     * The identifier of the Card to be authorized.
     */
    public function withCardID(string $cardID): self
    {
        $self = clone $this;
        $self['cardID'] = $cardID;

        return $self;
    }

    /**
     * Forces a card decline with a specific reason. No real time decision will be sent.
     *
     * @param DeclineReason|value-of<DeclineReason> $declineReason
     */
    public function withDeclineReason(DeclineReason|string $declineReason): self
    {
        $self = clone $this;
        $self['declineReason'] = $declineReason;

        return $self;
    }

    /**
     * The identifier of the Digital Wallet Token to be authorized.
     */
    public function withDigitalWalletTokenID(string $digitalWalletTokenID): self
    {
        $self = clone $this;
        $self['digitalWalletTokenID'] = $digitalWalletTokenID;

        return $self;
    }

    /**
     * The identifier of the Event Subscription to use. If provided, will override the default real time event subscription. Because you can only create one real time decision event subscription, you can use this field to route events to any specified event subscription for testing purposes.
     */
    public function withEventSubscriptionID(string $eventSubscriptionID): self
    {
        $self = clone $this;
        $self['eventSubscriptionID'] = $eventSubscriptionID;

        return $self;
    }

    /**
     * The merchant identifier (commonly abbreviated as MID) of the merchant the card is transacting with.
     */
    public function withMerchantAcceptorID(string $merchantAcceptorID): self
    {
        $self = clone $this;
        $self['merchantAcceptorID'] = $merchantAcceptorID;

        return $self;
    }

    /**
     * The Merchant Category Code (commonly abbreviated as MCC) of the merchant the card is transacting with.
     */
    public function withMerchantCategoryCode(string $merchantCategoryCode): self
    {
        $self = clone $this;
        $self['merchantCategoryCode'] = $merchantCategoryCode;

        return $self;
    }

    /**
     * The city the merchant resides in.
     */
    public function withMerchantCity(string $merchantCity): self
    {
        $self = clone $this;
        $self['merchantCity'] = $merchantCity;

        return $self;
    }

    /**
     * The country the merchant resides in.
     */
    public function withMerchantCountry(string $merchantCountry): self
    {
        $self = clone $this;
        $self['merchantCountry'] = $merchantCountry;

        return $self;
    }

    /**
     * The merchant descriptor of the merchant the card is transacting with.
     */
    public function withMerchantDescriptor(string $merchantDescriptor): self
    {
        $self = clone $this;
        $self['merchantDescriptor'] = $merchantDescriptor;

        return $self;
    }

    /**
     * The state the merchant resides in.
     */
    public function withMerchantState(string $merchantState): self
    {
        $self = clone $this;
        $self['merchantState'] = $merchantState;

        return $self;
    }

    /**
     * Fields specific to a given card network.
     *
     * @param NetworkDetails|NetworkDetailsShape $networkDetails
     */
    public function withNetworkDetails(
        NetworkDetails|array $networkDetails
    ): self {
        $self = clone $this;
        $self['networkDetails'] = $networkDetails;

        return $self;
    }

    /**
     * The risk score generated by the card network. For Visa this is the Visa Advanced Authorization risk score, from 0 to 99, where 99 is the riskiest.
     */
    public function withNetworkRiskScore(int $networkRiskScore): self
    {
        $self = clone $this;
        $self['networkRiskScore'] = $networkRiskScore;

        return $self;
    }

    /**
     * The identifier of the Physical Card to be authorized.
     */
    public function withPhysicalCardID(string $physicalCardID): self
    {
        $self = clone $this;
        $self['physicalCardID'] = $physicalCardID;

        return $self;
    }

    /**
     * The terminal identifier (commonly abbreviated as TID) of the terminal the card is transacting with.
     */
    public function withTerminalID(string $terminalID): self
    {
        $self = clone $this;
        $self['terminalID'] = $terminalID;

        return $self;
    }
}
