<?php

declare(strict_types=1);

namespace Increase\ServiceContracts\Simulations;

use Increase\CardPayments\CardPayment;
use Increase\Core\Exceptions\APIException;
use Increase\RequestOptions;
use Increase\Simulations\CardBalanceInquiries\CardBalanceInquiryCreateParams\DeclineReason;
use Increase\Simulations\CardBalanceInquiries\CardBalanceInquiryCreateParams\NetworkDetails;

/**
 * @phpstan-import-type NetworkDetailsShape from \Increase\Simulations\CardBalanceInquiries\CardBalanceInquiryCreateParams\NetworkDetails
 * @phpstan-import-type RequestOpts from \Increase\RequestOptions
 */
interface CardBalanceInquiriesContract
{
    /**
     * @api
     *
     * @param int $balance The balance amount in cents. The account balance will be used if not provided.
     * @param string $cardID the identifier of the Card to be authorized
     * @param DeclineReason|value-of<DeclineReason> $declineReason Forces a card decline with a specific reason. No real time decision will be sent.
     * @param string $digitalWalletTokenID the identifier of the Digital Wallet Token to be authorized
     * @param string $eventSubscriptionID The identifier of the Event Subscription to use. If provided, will override the default real time event subscription. Because you can only create one real time decision event subscription, you can use this field to route events to any specified event subscription for testing purposes.
     * @param string $merchantAcceptorID the merchant identifier (commonly abbreviated as MID) of the merchant the card is transacting with
     * @param string $merchantCategoryCode the Merchant Category Code (commonly abbreviated as MCC) of the merchant the card is transacting with
     * @param string $merchantCity the city the merchant resides in
     * @param string $merchantCountry the country the merchant resides in
     * @param string $merchantDescriptor the merchant descriptor of the merchant the card is transacting with
     * @param string $merchantState the state the merchant resides in
     * @param NetworkDetails|NetworkDetailsShape $networkDetails fields specific to a given card network
     * @param int $networkRiskScore The risk score generated by the card network. For Visa this is the Visa Advanced Authorization risk score, from 0 to 99, where 99 is the riskiest.
     * @param string $physicalCardID the identifier of the Physical Card to be authorized
     * @param string $terminalID the terminal identifier (commonly abbreviated as TID) of the terminal the card is transacting with
     * @param RequestOpts|null $requestOptions
     *
     * @throws APIException
     */
    public function create(
        ?int $balance = null,
        ?string $cardID = null,
        DeclineReason|string|null $declineReason = null,
        ?string $digitalWalletTokenID = null,
        ?string $eventSubscriptionID = null,
        ?string $merchantAcceptorID = null,
        ?string $merchantCategoryCode = null,
        ?string $merchantCity = null,
        ?string $merchantCountry = null,
        ?string $merchantDescriptor = null,
        ?string $merchantState = null,
        NetworkDetails|array|null $networkDetails = null,
        ?int $networkRiskScore = null,
        ?string $physicalCardID = null,
        ?string $terminalID = null,
        RequestOptions|array|null $requestOptions = null,
    ): CardPayment;
}
