<?php

declare(strict_types=1);

namespace Increase\CardPayments\CardPayment\Element;

use Increase\CardPayments\CardPayment\Element\CardIncrement\Actioner;
use Increase\CardPayments\CardPayment\Element\CardIncrement\AdditionalAmounts;
use Increase\CardPayments\CardPayment\Element\CardIncrement\Currency;
use Increase\CardPayments\CardPayment\Element\CardIncrement\Network;
use Increase\CardPayments\CardPayment\Element\CardIncrement\NetworkIdentifiers;
use Increase\CardPayments\CardPayment\Element\CardIncrement\Type;
use Increase\Core\Attributes\Required;
use Increase\Core\Concerns\SdkModel;
use Increase\Core\Contracts\BaseModel;

/**
 * A Card Increment object. This field will be present in the JSON response if and only if `category` is equal to `card_increment`. Card Increments increase the pending amount of an authorized transaction.
 *
 * @phpstan-import-type AdditionalAmountsShape from \Increase\CardPayments\CardPayment\Element\CardIncrement\AdditionalAmounts
 * @phpstan-import-type NetworkIdentifiersShape from \Increase\CardPayments\CardPayment\Element\CardIncrement\NetworkIdentifiers
 *
 * @phpstan-type CardIncrementShape = array{
 *   id: string,
 *   actioner: Actioner|value-of<Actioner>,
 *   additionalAmounts: AdditionalAmounts|AdditionalAmountsShape,
 *   amount: int,
 *   cardAuthorizationID: string,
 *   currency: Currency|value-of<Currency>,
 *   network: Network|value-of<Network>,
 *   networkIdentifiers: NetworkIdentifiers|NetworkIdentifiersShape,
 *   networkRiskScore: int|null,
 *   pendingTransactionID: string|null,
 *   presentmentAmount: int,
 *   presentmentCurrency: string,
 *   realTimeDecisionID: string|null,
 *   type: Type|value-of<Type>,
 *   updatedAuthorizationAmount: int,
 * }
 */
final class CardIncrement implements BaseModel
{
    /** @use SdkModel<CardIncrementShape> */
    use SdkModel;

    /**
     * The Card Increment identifier.
     */
    #[Required]
    public string $id;

    /**
     * Whether this authorization was approved by Increase, the card network through stand-in processing, or the user through a real-time decision.
     *
     * @var value-of<Actioner> $actioner
     */
    #[Required(enum: Actioner::class)]
    public string $actioner;

    /**
     * Additional amounts associated with the card authorization, such as ATM surcharges fees. These are usually a subset of the `amount` field and are used to provide more detailed information about the transaction.
     */
    #[Required('additional_amounts')]
    public AdditionalAmounts $additionalAmounts;

    /**
     * The amount of this increment in the minor unit of the transaction's currency. For dollars, for example, this is cents.
     */
    #[Required]
    public int $amount;

    /**
     * The identifier for the Card Authorization this increments.
     */
    #[Required('card_authorization_id')]
    public string $cardAuthorizationID;

    /**
     * The [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) code for the increment's currency.
     *
     * @var value-of<Currency> $currency
     */
    #[Required(enum: Currency::class)]
    public string $currency;

    /**
     * The card network used to process this card authorization.
     *
     * @var value-of<Network> $network
     */
    #[Required(enum: Network::class)]
    public string $network;

    /**
     * Network-specific identifiers for a specific request or transaction.
     */
    #[Required('network_identifiers')]
    public NetworkIdentifiers $networkIdentifiers;

    /**
     * The risk score generated by the card network. For Visa this is the Visa Advanced Authorization risk score, from 0 to 99, where 99 is the riskiest.
     */
    #[Required('network_risk_score')]
    public ?int $networkRiskScore;

    /**
     * The identifier of the Pending Transaction associated with this Card Increment.
     */
    #[Required('pending_transaction_id')]
    public ?string $pendingTransactionID;

    /**
     * The amount of this increment in the minor unit of the transaction's presentment currency.
     */
    #[Required('presentment_amount')]
    public int $presentmentAmount;

    /**
     * The [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) code for the transaction's presentment currency.
     */
    #[Required('presentment_currency')]
    public string $presentmentCurrency;

    /**
     * The identifier of the Real-Time Decision sent to approve or decline this incremental authorization.
     */
    #[Required('real_time_decision_id')]
    public ?string $realTimeDecisionID;

    /**
     * A constant representing the object's type. For this resource it will always be `card_increment`.
     *
     * @var value-of<Type> $type
     */
    #[Required(enum: Type::class)]
    public string $type;

    /**
     * The updated authorization amount after this increment, in the minor unit of the transaction's currency. For dollars, for example, this is cents.
     */
    #[Required('updated_authorization_amount')]
    public int $updatedAuthorizationAmount;

    /**
     * `new CardIncrement()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * CardIncrement::with(
     *   id: ...,
     *   actioner: ...,
     *   additionalAmounts: ...,
     *   amount: ...,
     *   cardAuthorizationID: ...,
     *   currency: ...,
     *   network: ...,
     *   networkIdentifiers: ...,
     *   networkRiskScore: ...,
     *   pendingTransactionID: ...,
     *   presentmentAmount: ...,
     *   presentmentCurrency: ...,
     *   realTimeDecisionID: ...,
     *   type: ...,
     *   updatedAuthorizationAmount: ...,
     * )
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new CardIncrement)
     *   ->withID(...)
     *   ->withActioner(...)
     *   ->withAdditionalAmounts(...)
     *   ->withAmount(...)
     *   ->withCardAuthorizationID(...)
     *   ->withCurrency(...)
     *   ->withNetwork(...)
     *   ->withNetworkIdentifiers(...)
     *   ->withNetworkRiskScore(...)
     *   ->withPendingTransactionID(...)
     *   ->withPresentmentAmount(...)
     *   ->withPresentmentCurrency(...)
     *   ->withRealTimeDecisionID(...)
     *   ->withType(...)
     *   ->withUpdatedAuthorizationAmount(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param Actioner|value-of<Actioner> $actioner
     * @param AdditionalAmounts|AdditionalAmountsShape $additionalAmounts
     * @param Currency|value-of<Currency> $currency
     * @param Network|value-of<Network> $network
     * @param NetworkIdentifiers|NetworkIdentifiersShape $networkIdentifiers
     * @param Type|value-of<Type> $type
     */
    public static function with(
        string $id,
        Actioner|string $actioner,
        AdditionalAmounts|array $additionalAmounts,
        int $amount,
        string $cardAuthorizationID,
        Currency|string $currency,
        Network|string $network,
        NetworkIdentifiers|array $networkIdentifiers,
        ?int $networkRiskScore,
        ?string $pendingTransactionID,
        int $presentmentAmount,
        string $presentmentCurrency,
        ?string $realTimeDecisionID,
        Type|string $type,
        int $updatedAuthorizationAmount,
    ): self {
        $self = new self;

        $self['id'] = $id;
        $self['actioner'] = $actioner;
        $self['additionalAmounts'] = $additionalAmounts;
        $self['amount'] = $amount;
        $self['cardAuthorizationID'] = $cardAuthorizationID;
        $self['currency'] = $currency;
        $self['network'] = $network;
        $self['networkIdentifiers'] = $networkIdentifiers;
        $self['networkRiskScore'] = $networkRiskScore;
        $self['pendingTransactionID'] = $pendingTransactionID;
        $self['presentmentAmount'] = $presentmentAmount;
        $self['presentmentCurrency'] = $presentmentCurrency;
        $self['realTimeDecisionID'] = $realTimeDecisionID;
        $self['type'] = $type;
        $self['updatedAuthorizationAmount'] = $updatedAuthorizationAmount;

        return $self;
    }

    /**
     * The Card Increment identifier.
     */
    public function withID(string $id): self
    {
        $self = clone $this;
        $self['id'] = $id;

        return $self;
    }

    /**
     * Whether this authorization was approved by Increase, the card network through stand-in processing, or the user through a real-time decision.
     *
     * @param Actioner|value-of<Actioner> $actioner
     */
    public function withActioner(Actioner|string $actioner): self
    {
        $self = clone $this;
        $self['actioner'] = $actioner;

        return $self;
    }

    /**
     * Additional amounts associated with the card authorization, such as ATM surcharges fees. These are usually a subset of the `amount` field and are used to provide more detailed information about the transaction.
     *
     * @param AdditionalAmounts|AdditionalAmountsShape $additionalAmounts
     */
    public function withAdditionalAmounts(
        AdditionalAmounts|array $additionalAmounts
    ): self {
        $self = clone $this;
        $self['additionalAmounts'] = $additionalAmounts;

        return $self;
    }

    /**
     * The amount of this increment in the minor unit of the transaction's currency. For dollars, for example, this is cents.
     */
    public function withAmount(int $amount): self
    {
        $self = clone $this;
        $self['amount'] = $amount;

        return $self;
    }

    /**
     * The identifier for the Card Authorization this increments.
     */
    public function withCardAuthorizationID(string $cardAuthorizationID): self
    {
        $self = clone $this;
        $self['cardAuthorizationID'] = $cardAuthorizationID;

        return $self;
    }

    /**
     * The [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) code for the increment's currency.
     *
     * @param Currency|value-of<Currency> $currency
     */
    public function withCurrency(Currency|string $currency): self
    {
        $self = clone $this;
        $self['currency'] = $currency;

        return $self;
    }

    /**
     * The card network used to process this card authorization.
     *
     * @param Network|value-of<Network> $network
     */
    public function withNetwork(Network|string $network): self
    {
        $self = clone $this;
        $self['network'] = $network;

        return $self;
    }

    /**
     * Network-specific identifiers for a specific request or transaction.
     *
     * @param NetworkIdentifiers|NetworkIdentifiersShape $networkIdentifiers
     */
    public function withNetworkIdentifiers(
        NetworkIdentifiers|array $networkIdentifiers
    ): self {
        $self = clone $this;
        $self['networkIdentifiers'] = $networkIdentifiers;

        return $self;
    }

    /**
     * The risk score generated by the card network. For Visa this is the Visa Advanced Authorization risk score, from 0 to 99, where 99 is the riskiest.
     */
    public function withNetworkRiskScore(?int $networkRiskScore): self
    {
        $self = clone $this;
        $self['networkRiskScore'] = $networkRiskScore;

        return $self;
    }

    /**
     * The identifier of the Pending Transaction associated with this Card Increment.
     */
    public function withPendingTransactionID(
        ?string $pendingTransactionID
    ): self {
        $self = clone $this;
        $self['pendingTransactionID'] = $pendingTransactionID;

        return $self;
    }

    /**
     * The amount of this increment in the minor unit of the transaction's presentment currency.
     */
    public function withPresentmentAmount(int $presentmentAmount): self
    {
        $self = clone $this;
        $self['presentmentAmount'] = $presentmentAmount;

        return $self;
    }

    /**
     * The [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) code for the transaction's presentment currency.
     */
    public function withPresentmentCurrency(string $presentmentCurrency): self
    {
        $self = clone $this;
        $self['presentmentCurrency'] = $presentmentCurrency;

        return $self;
    }

    /**
     * The identifier of the Real-Time Decision sent to approve or decline this incremental authorization.
     */
    public function withRealTimeDecisionID(?string $realTimeDecisionID): self
    {
        $self = clone $this;
        $self['realTimeDecisionID'] = $realTimeDecisionID;

        return $self;
    }

    /**
     * A constant representing the object's type. For this resource it will always be `card_increment`.
     *
     * @param Type|value-of<Type> $type
     */
    public function withType(Type|string $type): self
    {
        $self = clone $this;
        $self['type'] = $type;

        return $self;
    }

    /**
     * The updated authorization amount after this increment, in the minor unit of the transaction's currency. For dollars, for example, this is cents.
     */
    public function withUpdatedAuthorizationAmount(
        int $updatedAuthorizationAmount
    ): self {
        $self = clone $this;
        $self['updatedAuthorizationAmount'] = $updatedAuthorizationAmount;

        return $self;
    }
}
