<?php

declare(strict_types=1);

namespace Increase\ACHTransfers\ACHTransfer;

use Increase\ACHTransfers\ACHTransfer\Return_\ReturnReasonCode;
use Increase\Core\Attributes\Required;
use Increase\Core\Concerns\SdkModel;
use Increase\Core\Contracts\BaseModel;

/**
 * If your transfer is returned, this will contain details of the return.
 *
 * @phpstan-type ReturnShape = array{
 *   createdAt: \DateTimeInterface,
 *   rawReturnReasonCode: string,
 *   returnReasonCode: ReturnReasonCode|value-of<ReturnReasonCode>,
 *   traceNumber: string,
 *   transactionID: string,
 *   transferID: string,
 * }
 */
final class Return_ implements BaseModel
{
    /** @use SdkModel<ReturnShape> */
    use SdkModel;

    /**
     * The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date and time at which the transfer was created.
     */
    #[Required('created_at')]
    public \DateTimeInterface $createdAt;

    /**
     * The three character ACH return code, in the range R01 to R85.
     */
    #[Required('raw_return_reason_code')]
    public string $rawReturnReasonCode;

    /**
     * Why the ACH Transfer was returned. This reason code is sent by the receiving bank back to Increase.
     *
     * @var value-of<ReturnReasonCode> $returnReasonCode
     */
    #[Required('return_reason_code', enum: ReturnReasonCode::class)]
    public string $returnReasonCode;

    /**
     * A 15 digit number that was generated by the bank that initiated the return. The trace number of the return is different than that of the original transfer. ACH trace numbers are not unique, but along with the amount and date this number can be used to identify the ACH return at the bank that initiated it.
     */
    #[Required('trace_number')]
    public string $traceNumber;

    /**
     * The identifier of the Transaction associated with this return.
     */
    #[Required('transaction_id')]
    public string $transactionID;

    /**
     * The identifier of the ACH Transfer associated with this return.
     */
    #[Required('transfer_id')]
    public string $transferID;

    /**
     * `new Return_()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * Return_::with(
     *   createdAt: ...,
     *   rawReturnReasonCode: ...,
     *   returnReasonCode: ...,
     *   traceNumber: ...,
     *   transactionID: ...,
     *   transferID: ...,
     * )
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new Return_)
     *   ->withCreatedAt(...)
     *   ->withRawReturnReasonCode(...)
     *   ->withReturnReasonCode(...)
     *   ->withTraceNumber(...)
     *   ->withTransactionID(...)
     *   ->withTransferID(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param ReturnReasonCode|value-of<ReturnReasonCode> $returnReasonCode
     */
    public static function with(
        \DateTimeInterface $createdAt,
        string $rawReturnReasonCode,
        ReturnReasonCode|string $returnReasonCode,
        string $traceNumber,
        string $transactionID,
        string $transferID,
    ): self {
        $self = new self;

        $self['createdAt'] = $createdAt;
        $self['rawReturnReasonCode'] = $rawReturnReasonCode;
        $self['returnReasonCode'] = $returnReasonCode;
        $self['traceNumber'] = $traceNumber;
        $self['transactionID'] = $transactionID;
        $self['transferID'] = $transferID;

        return $self;
    }

    /**
     * The [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date and time at which the transfer was created.
     */
    public function withCreatedAt(\DateTimeInterface $createdAt): self
    {
        $self = clone $this;
        $self['createdAt'] = $createdAt;

        return $self;
    }

    /**
     * The three character ACH return code, in the range R01 to R85.
     */
    public function withRawReturnReasonCode(string $rawReturnReasonCode): self
    {
        $self = clone $this;
        $self['rawReturnReasonCode'] = $rawReturnReasonCode;

        return $self;
    }

    /**
     * Why the ACH Transfer was returned. This reason code is sent by the receiving bank back to Increase.
     *
     * @param ReturnReasonCode|value-of<ReturnReasonCode> $returnReasonCode
     */
    public function withReturnReasonCode(
        ReturnReasonCode|string $returnReasonCode
    ): self {
        $self = clone $this;
        $self['returnReasonCode'] = $returnReasonCode;

        return $self;
    }

    /**
     * A 15 digit number that was generated by the bank that initiated the return. The trace number of the return is different than that of the original transfer. ACH trace numbers are not unique, but along with the amount and date this number can be used to identify the ACH return at the bank that initiated it.
     */
    public function withTraceNumber(string $traceNumber): self
    {
        $self = clone $this;
        $self['traceNumber'] = $traceNumber;

        return $self;
    }

    /**
     * The identifier of the Transaction associated with this return.
     */
    public function withTransactionID(string $transactionID): self
    {
        $self = clone $this;
        $self['transactionID'] = $transactionID;

        return $self;
    }

    /**
     * The identifier of the ACH Transfer associated with this return.
     */
    public function withTransferID(string $transferID): self
    {
        $self = clone $this;
        $self['transferID'] = $transferID;

        return $self;
    }
}
