<?php

declare(strict_types=1);

namespace Increase\Simulations\CardAuthorizations;

use Increase\Core\Attributes\Optional;
use Increase\Core\Attributes\Required;
use Increase\Core\Concerns\SdkModel;
use Increase\Core\Concerns\SdkParams;
use Increase\Core\Contracts\BaseModel;
use Increase\Simulations\CardAuthorizations\CardAuthorizationCreateParams\DeclineReason;
use Increase\Simulations\CardAuthorizations\CardAuthorizationCreateParams\NetworkDetails;
use Increase\Simulations\CardAuthorizations\CardAuthorizationCreateParams\ProcessingCategory;

/**
 * Simulates a purchase authorization on a [Card](#cards). Depending on the balance available to the card and the `amount` submitted, the authorization activity will result in a [Pending Transaction](#pending-transactions) of type `card_authorization` or a [Declined Transaction](#declined-transactions) of type `card_decline`. You can pass either a Card id or a [Digital Wallet Token](#digital-wallet-tokens) id to simulate the two different ways purchases can be made.
 *
 * @see Increase\Services\Simulations\CardAuthorizationsService::create()
 *
 * @phpstan-import-type NetworkDetailsShape from \Increase\Simulations\CardAuthorizations\CardAuthorizationCreateParams\NetworkDetails
 * @phpstan-import-type ProcessingCategoryShape from \Increase\Simulations\CardAuthorizations\CardAuthorizationCreateParams\ProcessingCategory
 *
 * @phpstan-type CardAuthorizationCreateParamsShape = array{
 *   amount: int,
 *   authenticatedCardPaymentID?: string|null,
 *   cardID?: string|null,
 *   declineReason?: null|DeclineReason|value-of<DeclineReason>,
 *   digitalWalletTokenID?: string|null,
 *   eventSubscriptionID?: string|null,
 *   merchantAcceptorID?: string|null,
 *   merchantCategoryCode?: string|null,
 *   merchantCity?: string|null,
 *   merchantCountry?: string|null,
 *   merchantDescriptor?: string|null,
 *   merchantState?: string|null,
 *   networkDetails?: null|NetworkDetails|NetworkDetailsShape,
 *   networkRiskScore?: int|null,
 *   physicalCardID?: string|null,
 *   processingCategory?: null|ProcessingCategory|ProcessingCategoryShape,
 *   terminalID?: string|null,
 * }
 */
final class CardAuthorizationCreateParams implements BaseModel
{
    /** @use SdkModel<CardAuthorizationCreateParamsShape> */
    use SdkModel;
    use SdkParams;

    /**
     * The authorization amount in cents.
     */
    #[Required]
    public int $amount;

    /**
     * The identifier of a Card Payment with a `card_authentication` if you want to simulate an authenticated authorization.
     */
    #[Optional('authenticated_card_payment_id')]
    public ?string $authenticatedCardPaymentID;

    /**
     * The identifier of the Card to be authorized.
     */
    #[Optional('card_id')]
    public ?string $cardID;

    /**
     * Forces a card decline with a specific reason. No real time decision will be sent.
     *
     * @var value-of<DeclineReason>|null $declineReason
     */
    #[Optional('decline_reason', enum: DeclineReason::class)]
    public ?string $declineReason;

    /**
     * The identifier of the Digital Wallet Token to be authorized.
     */
    #[Optional('digital_wallet_token_id')]
    public ?string $digitalWalletTokenID;

    /**
     * The identifier of the Event Subscription to use. If provided, will override the default real time event subscription. Because you can only create one real time decision event subscription, you can use this field to route events to any specified event subscription for testing purposes.
     */
    #[Optional('event_subscription_id')]
    public ?string $eventSubscriptionID;

    /**
     * The merchant identifier (commonly abbreviated as MID) of the merchant the card is transacting with.
     */
    #[Optional('merchant_acceptor_id')]
    public ?string $merchantAcceptorID;

    /**
     * The Merchant Category Code (commonly abbreviated as MCC) of the merchant the card is transacting with.
     */
    #[Optional('merchant_category_code')]
    public ?string $merchantCategoryCode;

    /**
     * The city the merchant resides in.
     */
    #[Optional('merchant_city')]
    public ?string $merchantCity;

    /**
     * The country the merchant resides in.
     */
    #[Optional('merchant_country')]
    public ?string $merchantCountry;

    /**
     * The merchant descriptor of the merchant the card is transacting with.
     */
    #[Optional('merchant_descriptor')]
    public ?string $merchantDescriptor;

    /**
     * The state the merchant resides in.
     */
    #[Optional('merchant_state')]
    public ?string $merchantState;

    /**
     * Fields specific to a given card network.
     */
    #[Optional('network_details')]
    public ?NetworkDetails $networkDetails;

    /**
     * The risk score generated by the card network. For Visa this is the Visa Advanced Authorization risk score, from 0 to 99, where 99 is the riskiest.
     */
    #[Optional('network_risk_score')]
    public ?int $networkRiskScore;

    /**
     * The identifier of the Physical Card to be authorized.
     */
    #[Optional('physical_card_id')]
    public ?string $physicalCardID;

    /**
     * Fields specific to a specific type of authorization, such as Automatic Fuel Dispensers, Refund Authorizations, or Cash Disbursements.
     */
    #[Optional('processing_category')]
    public ?ProcessingCategory $processingCategory;

    /**
     * The terminal identifier (commonly abbreviated as TID) of the terminal the card is transacting with.
     */
    #[Optional('terminal_id')]
    public ?string $terminalID;

    /**
     * `new CardAuthorizationCreateParams()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * CardAuthorizationCreateParams::with(amount: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new CardAuthorizationCreateParams)->withAmount(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param DeclineReason|value-of<DeclineReason>|null $declineReason
     * @param NetworkDetails|NetworkDetailsShape|null $networkDetails
     * @param ProcessingCategory|ProcessingCategoryShape|null $processingCategory
     */
    public static function with(
        int $amount,
        ?string $authenticatedCardPaymentID = null,
        ?string $cardID = null,
        DeclineReason|string|null $declineReason = null,
        ?string $digitalWalletTokenID = null,
        ?string $eventSubscriptionID = null,
        ?string $merchantAcceptorID = null,
        ?string $merchantCategoryCode = null,
        ?string $merchantCity = null,
        ?string $merchantCountry = null,
        ?string $merchantDescriptor = null,
        ?string $merchantState = null,
        NetworkDetails|array|null $networkDetails = null,
        ?int $networkRiskScore = null,
        ?string $physicalCardID = null,
        ProcessingCategory|array|null $processingCategory = null,
        ?string $terminalID = null,
    ): self {
        $self = new self;

        $self['amount'] = $amount;

        null !== $authenticatedCardPaymentID && $self['authenticatedCardPaymentID'] = $authenticatedCardPaymentID;
        null !== $cardID && $self['cardID'] = $cardID;
        null !== $declineReason && $self['declineReason'] = $declineReason;
        null !== $digitalWalletTokenID && $self['digitalWalletTokenID'] = $digitalWalletTokenID;
        null !== $eventSubscriptionID && $self['eventSubscriptionID'] = $eventSubscriptionID;
        null !== $merchantAcceptorID && $self['merchantAcceptorID'] = $merchantAcceptorID;
        null !== $merchantCategoryCode && $self['merchantCategoryCode'] = $merchantCategoryCode;
        null !== $merchantCity && $self['merchantCity'] = $merchantCity;
        null !== $merchantCountry && $self['merchantCountry'] = $merchantCountry;
        null !== $merchantDescriptor && $self['merchantDescriptor'] = $merchantDescriptor;
        null !== $merchantState && $self['merchantState'] = $merchantState;
        null !== $networkDetails && $self['networkDetails'] = $networkDetails;
        null !== $networkRiskScore && $self['networkRiskScore'] = $networkRiskScore;
        null !== $physicalCardID && $self['physicalCardID'] = $physicalCardID;
        null !== $processingCategory && $self['processingCategory'] = $processingCategory;
        null !== $terminalID && $self['terminalID'] = $terminalID;

        return $self;
    }

    /**
     * The authorization amount in cents.
     */
    public function withAmount(int $amount): self
    {
        $self = clone $this;
        $self['amount'] = $amount;

        return $self;
    }

    /**
     * The identifier of a Card Payment with a `card_authentication` if you want to simulate an authenticated authorization.
     */
    public function withAuthenticatedCardPaymentID(
        string $authenticatedCardPaymentID
    ): self {
        $self = clone $this;
        $self['authenticatedCardPaymentID'] = $authenticatedCardPaymentID;

        return $self;
    }

    /**
     * The identifier of the Card to be authorized.
     */
    public function withCardID(string $cardID): self
    {
        $self = clone $this;
        $self['cardID'] = $cardID;

        return $self;
    }

    /**
     * Forces a card decline with a specific reason. No real time decision will be sent.
     *
     * @param DeclineReason|value-of<DeclineReason> $declineReason
     */
    public function withDeclineReason(DeclineReason|string $declineReason): self
    {
        $self = clone $this;
        $self['declineReason'] = $declineReason;

        return $self;
    }

    /**
     * The identifier of the Digital Wallet Token to be authorized.
     */
    public function withDigitalWalletTokenID(string $digitalWalletTokenID): self
    {
        $self = clone $this;
        $self['digitalWalletTokenID'] = $digitalWalletTokenID;

        return $self;
    }

    /**
     * The identifier of the Event Subscription to use. If provided, will override the default real time event subscription. Because you can only create one real time decision event subscription, you can use this field to route events to any specified event subscription for testing purposes.
     */
    public function withEventSubscriptionID(string $eventSubscriptionID): self
    {
        $self = clone $this;
        $self['eventSubscriptionID'] = $eventSubscriptionID;

        return $self;
    }

    /**
     * The merchant identifier (commonly abbreviated as MID) of the merchant the card is transacting with.
     */
    public function withMerchantAcceptorID(string $merchantAcceptorID): self
    {
        $self = clone $this;
        $self['merchantAcceptorID'] = $merchantAcceptorID;

        return $self;
    }

    /**
     * The Merchant Category Code (commonly abbreviated as MCC) of the merchant the card is transacting with.
     */
    public function withMerchantCategoryCode(string $merchantCategoryCode): self
    {
        $self = clone $this;
        $self['merchantCategoryCode'] = $merchantCategoryCode;

        return $self;
    }

    /**
     * The city the merchant resides in.
     */
    public function withMerchantCity(string $merchantCity): self
    {
        $self = clone $this;
        $self['merchantCity'] = $merchantCity;

        return $self;
    }

    /**
     * The country the merchant resides in.
     */
    public function withMerchantCountry(string $merchantCountry): self
    {
        $self = clone $this;
        $self['merchantCountry'] = $merchantCountry;

        return $self;
    }

    /**
     * The merchant descriptor of the merchant the card is transacting with.
     */
    public function withMerchantDescriptor(string $merchantDescriptor): self
    {
        $self = clone $this;
        $self['merchantDescriptor'] = $merchantDescriptor;

        return $self;
    }

    /**
     * The state the merchant resides in.
     */
    public function withMerchantState(string $merchantState): self
    {
        $self = clone $this;
        $self['merchantState'] = $merchantState;

        return $self;
    }

    /**
     * Fields specific to a given card network.
     *
     * @param NetworkDetails|NetworkDetailsShape $networkDetails
     */
    public function withNetworkDetails(
        NetworkDetails|array $networkDetails
    ): self {
        $self = clone $this;
        $self['networkDetails'] = $networkDetails;

        return $self;
    }

    /**
     * The risk score generated by the card network. For Visa this is the Visa Advanced Authorization risk score, from 0 to 99, where 99 is the riskiest.
     */
    public function withNetworkRiskScore(int $networkRiskScore): self
    {
        $self = clone $this;
        $self['networkRiskScore'] = $networkRiskScore;

        return $self;
    }

    /**
     * The identifier of the Physical Card to be authorized.
     */
    public function withPhysicalCardID(string $physicalCardID): self
    {
        $self = clone $this;
        $self['physicalCardID'] = $physicalCardID;

        return $self;
    }

    /**
     * Fields specific to a specific type of authorization, such as Automatic Fuel Dispensers, Refund Authorizations, or Cash Disbursements.
     *
     * @param ProcessingCategory|ProcessingCategoryShape $processingCategory
     */
    public function withProcessingCategory(
        ProcessingCategory|array $processingCategory
    ): self {
        $self = clone $this;
        $self['processingCategory'] = $processingCategory;

        return $self;
    }

    /**
     * The terminal identifier (commonly abbreviated as TID) of the terminal the card is transacting with.
     */
    public function withTerminalID(string $terminalID): self
    {
        $self = clone $this;
        $self['terminalID'] = $terminalID;

        return $self;
    }
}
