<?php

declare(strict_types=1);

namespace Increase\ServiceContracts;

use Increase\Core\Exceptions\APIException;
use Increase\OAuthTokens\OAuthToken;
use Increase\OAuthTokens\OAuthTokenCreateParams\GrantType;
use Increase\RequestOptions;

/**
 * @phpstan-import-type RequestOpts from \Increase\RequestOptions
 */
interface OAuthTokensContract
{
    /**
     * @api
     *
     * @param GrantType|value-of<GrantType> $grantType The credential you request in exchange for the code. In Production, this is always `authorization_code`. In Sandbox, you can pass either enum value.
     * @param string $clientID the public identifier for your application
     * @param string $clientSecret The secret that confirms you own the application. This is redundant given that the request is made with your API key but it's a required component of OAuth 2.0.
     * @param string $code the authorization code generated by the user and given to you as a query parameter
     * @param string $productionToken The production token you want to exchange for a sandbox token. This is only available in Sandbox. Set `grant_type` to `production_token` to use this parameter.
     * @param RequestOpts|null $requestOptions
     *
     * @throws APIException
     */
    public function create(
        GrantType|string $grantType,
        ?string $clientID = null,
        ?string $clientSecret = null,
        ?string $code = null,
        ?string $productionToken = null,
        RequestOptions|array|null $requestOptions = null,
    ): OAuthToken;
}
