<?php

declare(strict_types=1);

namespace Increase\Files;

use Increase\Core\Attributes\Required;
use Increase\Core\Concerns\SdkModel;
use Increase\Core\Contracts\BaseModel;
use Increase\Files\File\Direction;
use Increase\Files\File\Purpose;
use Increase\Files\File\Type;

/**
 * Files are objects that represent a file hosted on Increase's servers. The file may have been uploaded by you (for example, when uploading a check image) or it may have been created by Increase (for example, an autogenerated statement PDF). If you need to download a File, create a File Link.
 *
 * @phpstan-type FileShape = array{
 *   id: string,
 *   createdAt: \DateTimeInterface,
 *   description: string|null,
 *   direction: Direction|value-of<Direction>,
 *   filename: string|null,
 *   idempotencyKey: string|null,
 *   mimeType: string,
 *   purpose: Purpose|value-of<Purpose>,
 *   type: Type|value-of<Type>,
 * }
 */
final class File implements BaseModel
{
    /** @use SdkModel<FileShape> */
    use SdkModel;

    /**
     * The File's identifier.
     */
    #[Required]
    public string $id;

    /**
     * The time the File was created.
     */
    #[Required('created_at')]
    public \DateTimeInterface $createdAt;

    /**
     * A description of the File.
     */
    #[Required]
    public ?string $description;

    /**
     * Whether the File was generated by Increase or by you and sent to Increase.
     *
     * @var value-of<Direction> $direction
     */
    #[Required(enum: Direction::class)]
    public string $direction;

    /**
     * The filename that was provided upon upload or generated by Increase.
     */
    #[Required]
    public ?string $filename;

    /**
     * The idempotency key you chose for this object. This value is unique across Increase and is used to ensure that a request is only processed once. Learn more about [idempotency](https://increase.com/documentation/idempotency-keys).
     */
    #[Required('idempotency_key')]
    public ?string $idempotencyKey;

    /**
     * The MIME type of the file.
     */
    #[Required('mime_type')]
    public string $mimeType;

    /**
     * What the File will be used for. We may add additional possible values for this enum over time; your application should be able to handle such additions gracefully.
     *
     * @var value-of<Purpose> $purpose
     */
    #[Required(enum: Purpose::class)]
    public string $purpose;

    /**
     * A constant representing the object's type. For this resource it will always be `file`.
     *
     * @var value-of<Type> $type
     */
    #[Required(enum: Type::class)]
    public string $type;

    /**
     * `new File()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * File::with(
     *   id: ...,
     *   createdAt: ...,
     *   description: ...,
     *   direction: ...,
     *   filename: ...,
     *   idempotencyKey: ...,
     *   mimeType: ...,
     *   purpose: ...,
     *   type: ...,
     * )
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new File)
     *   ->withID(...)
     *   ->withCreatedAt(...)
     *   ->withDescription(...)
     *   ->withDirection(...)
     *   ->withFilename(...)
     *   ->withIdempotencyKey(...)
     *   ->withMimeType(...)
     *   ->withPurpose(...)
     *   ->withType(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param Direction|value-of<Direction> $direction
     * @param Purpose|value-of<Purpose> $purpose
     * @param Type|value-of<Type> $type
     */
    public static function with(
        string $id,
        \DateTimeInterface $createdAt,
        ?string $description,
        Direction|string $direction,
        ?string $filename,
        ?string $idempotencyKey,
        string $mimeType,
        Purpose|string $purpose,
        Type|string $type,
    ): self {
        $self = new self;

        $self['id'] = $id;
        $self['createdAt'] = $createdAt;
        $self['description'] = $description;
        $self['direction'] = $direction;
        $self['filename'] = $filename;
        $self['idempotencyKey'] = $idempotencyKey;
        $self['mimeType'] = $mimeType;
        $self['purpose'] = $purpose;
        $self['type'] = $type;

        return $self;
    }

    /**
     * The File's identifier.
     */
    public function withID(string $id): self
    {
        $self = clone $this;
        $self['id'] = $id;

        return $self;
    }

    /**
     * The time the File was created.
     */
    public function withCreatedAt(\DateTimeInterface $createdAt): self
    {
        $self = clone $this;
        $self['createdAt'] = $createdAt;

        return $self;
    }

    /**
     * A description of the File.
     */
    public function withDescription(?string $description): self
    {
        $self = clone $this;
        $self['description'] = $description;

        return $self;
    }

    /**
     * Whether the File was generated by Increase or by you and sent to Increase.
     *
     * @param Direction|value-of<Direction> $direction
     */
    public function withDirection(Direction|string $direction): self
    {
        $self = clone $this;
        $self['direction'] = $direction;

        return $self;
    }

    /**
     * The filename that was provided upon upload or generated by Increase.
     */
    public function withFilename(?string $filename): self
    {
        $self = clone $this;
        $self['filename'] = $filename;

        return $self;
    }

    /**
     * The idempotency key you chose for this object. This value is unique across Increase and is used to ensure that a request is only processed once. Learn more about [idempotency](https://increase.com/documentation/idempotency-keys).
     */
    public function withIdempotencyKey(?string $idempotencyKey): self
    {
        $self = clone $this;
        $self['idempotencyKey'] = $idempotencyKey;

        return $self;
    }

    /**
     * The MIME type of the file.
     */
    public function withMimeType(string $mimeType): self
    {
        $self = clone $this;
        $self['mimeType'] = $mimeType;

        return $self;
    }

    /**
     * What the File will be used for. We may add additional possible values for this enum over time; your application should be able to handle such additions gracefully.
     *
     * @param Purpose|value-of<Purpose> $purpose
     */
    public function withPurpose(Purpose|string $purpose): self
    {
        $self = clone $this;
        $self['purpose'] = $purpose;

        return $self;
    }

    /**
     * A constant representing the object's type. For this resource it will always be `file`.
     *
     * @param Type|value-of<Type> $type
     */
    public function withType(Type|string $type): self
    {
        $self = clone $this;
        $self['type'] = $type;

        return $self;
    }
}
