<?php

declare(strict_types=1);

namespace Increase\Services\Simulations;

use Increase\Client;
use Increase\Core\Exceptions\APIException;
use Increase\Core\Util;
use Increase\RequestOptions;
use Increase\ServiceContracts\Simulations\CardAuthorizationsContract;
use Increase\Simulations\CardAuthorizations\CardAuthorizationCreateParams\DeclineReason;
use Increase\Simulations\CardAuthorizations\CardAuthorizationCreateParams\NetworkDetails;
use Increase\Simulations\CardAuthorizations\CardAuthorizationCreateParams\ProcessingCategory;
use Increase\Simulations\CardAuthorizations\CardAuthorizationNewResponse;

/**
 * @phpstan-import-type NetworkDetailsShape from \Increase\Simulations\CardAuthorizations\CardAuthorizationCreateParams\NetworkDetails
 * @phpstan-import-type ProcessingCategoryShape from \Increase\Simulations\CardAuthorizations\CardAuthorizationCreateParams\ProcessingCategory
 * @phpstan-import-type RequestOpts from \Increase\RequestOptions
 */
final class CardAuthorizationsService implements CardAuthorizationsContract
{
    /**
     * @api
     */
    public CardAuthorizationsRawService $raw;

    /**
     * @internal
     */
    public function __construct(private Client $client)
    {
        $this->raw = new CardAuthorizationsRawService($client);
    }

    /**
     * @api
     *
     * Simulates a purchase authorization on a [Card](#cards). Depending on the balance available to the card and the `amount` submitted, the authorization activity will result in a [Pending Transaction](#pending-transactions) of type `card_authorization` or a [Declined Transaction](#declined-transactions) of type `card_decline`. You can pass either a Card id or a [Digital Wallet Token](#digital-wallet-tokens) id to simulate the two different ways purchases can be made.
     *
     * @param int $amount the authorization amount in cents
     * @param string $authenticatedCardPaymentID the identifier of a Card Payment with a `card_authentication` if you want to simulate an authenticated authorization
     * @param string $cardID the identifier of the Card to be authorized
     * @param DeclineReason|value-of<DeclineReason> $declineReason Forces a card decline with a specific reason. No real time decision will be sent.
     * @param string $digitalWalletTokenID the identifier of the Digital Wallet Token to be authorized
     * @param string $eventSubscriptionID The identifier of the Event Subscription to use. If provided, will override the default real time event subscription. Because you can only create one real time decision event subscription, you can use this field to route events to any specified event subscription for testing purposes.
     * @param string $merchantAcceptorID the merchant identifier (commonly abbreviated as MID) of the merchant the card is transacting with
     * @param string $merchantCategoryCode the Merchant Category Code (commonly abbreviated as MCC) of the merchant the card is transacting with
     * @param string $merchantCity the city the merchant resides in
     * @param string $merchantCountry the country the merchant resides in
     * @param string $merchantDescriptor the merchant descriptor of the merchant the card is transacting with
     * @param string $merchantState the state the merchant resides in
     * @param NetworkDetails|NetworkDetailsShape $networkDetails fields specific to a given card network
     * @param int $networkRiskScore The risk score generated by the card network. For Visa this is the Visa Advanced Authorization risk score, from 0 to 99, where 99 is the riskiest.
     * @param string $physicalCardID the identifier of the Physical Card to be authorized
     * @param ProcessingCategory|ProcessingCategoryShape $processingCategory fields specific to a specific type of authorization, such as Automatic Fuel Dispensers, Refund Authorizations, or Cash Disbursements
     * @param string $terminalID the terminal identifier (commonly abbreviated as TID) of the terminal the card is transacting with
     * @param RequestOpts|null $requestOptions
     *
     * @throws APIException
     */
    public function create(
        int $amount,
        ?string $authenticatedCardPaymentID = null,
        ?string $cardID = null,
        DeclineReason|string|null $declineReason = null,
        ?string $digitalWalletTokenID = null,
        ?string $eventSubscriptionID = null,
        ?string $merchantAcceptorID = null,
        ?string $merchantCategoryCode = null,
        ?string $merchantCity = null,
        ?string $merchantCountry = null,
        ?string $merchantDescriptor = null,
        ?string $merchantState = null,
        NetworkDetails|array|null $networkDetails = null,
        ?int $networkRiskScore = null,
        ?string $physicalCardID = null,
        ProcessingCategory|array|null $processingCategory = null,
        ?string $terminalID = null,
        RequestOptions|array|null $requestOptions = null,
    ): CardAuthorizationNewResponse {
        $params = Util::removeNulls(
            [
                'amount' => $amount,
                'authenticatedCardPaymentID' => $authenticatedCardPaymentID,
                'cardID' => $cardID,
                'declineReason' => $declineReason,
                'digitalWalletTokenID' => $digitalWalletTokenID,
                'eventSubscriptionID' => $eventSubscriptionID,
                'merchantAcceptorID' => $merchantAcceptorID,
                'merchantCategoryCode' => $merchantCategoryCode,
                'merchantCity' => $merchantCity,
                'merchantCountry' => $merchantCountry,
                'merchantDescriptor' => $merchantDescriptor,
                'merchantState' => $merchantState,
                'networkDetails' => $networkDetails,
                'networkRiskScore' => $networkRiskScore,
                'physicalCardID' => $physicalCardID,
                'processingCategory' => $processingCategory,
                'terminalID' => $terminalID,
            ],
        );

        // @phpstan-ignore-next-line argument.type
        $response = $this->raw->create(params: $params, requestOptions: $requestOptions);

        return $response->parse();
    }
}
