<?php

declare(strict_types=1);

namespace Increase\OAuthTokens;

use Increase\Core\Attributes\Optional;
use Increase\Core\Attributes\Required;
use Increase\Core\Concerns\SdkModel;
use Increase\Core\Concerns\SdkParams;
use Increase\Core\Contracts\BaseModel;
use Increase\OAuthTokens\OAuthTokenCreateParams\GrantType;

/**
 * Create an OAuth Token.
 *
 * @see Increase\Services\OAuthTokensService::create()
 *
 * @phpstan-type OAuthTokenCreateParamsShape = array{
 *   grantType: GrantType|value-of<GrantType>,
 *   clientID?: string|null,
 *   clientSecret?: string|null,
 *   code?: string|null,
 *   productionToken?: string|null,
 * }
 */
final class OAuthTokenCreateParams implements BaseModel
{
    /** @use SdkModel<OAuthTokenCreateParamsShape> */
    use SdkModel;
    use SdkParams;

    /**
     * The credential you request in exchange for the code. In Production, this is always `authorization_code`. In Sandbox, you can pass either enum value.
     *
     * @var value-of<GrantType> $grantType
     */
    #[Required('grant_type', enum: GrantType::class)]
    public string $grantType;

    /**
     * The public identifier for your application.
     */
    #[Optional('client_id')]
    public ?string $clientID;

    /**
     * The secret that confirms you own the application. This is redundant given that the request is made with your API key but it's a required component of OAuth 2.0.
     */
    #[Optional('client_secret')]
    public ?string $clientSecret;

    /**
     * The authorization code generated by the user and given to you as a query parameter.
     */
    #[Optional]
    public ?string $code;

    /**
     * The production token you want to exchange for a sandbox token. This is only available in Sandbox. Set `grant_type` to `production_token` to use this parameter.
     */
    #[Optional('production_token')]
    public ?string $productionToken;

    /**
     * `new OAuthTokenCreateParams()` is missing required properties by the API.
     *
     * To enforce required parameters use
     * ```
     * OAuthTokenCreateParams::with(grantType: ...)
     * ```
     *
     * Otherwise ensure the following setters are called
     *
     * ```
     * (new OAuthTokenCreateParams)->withGrantType(...)
     * ```
     */
    public function __construct()
    {
        $this->initialize();
    }

    /**
     * Construct an instance from the required parameters.
     *
     * You must use named parameters to construct any parameters with a default value.
     *
     * @param GrantType|value-of<GrantType> $grantType
     */
    public static function with(
        GrantType|string $grantType,
        ?string $clientID = null,
        ?string $clientSecret = null,
        ?string $code = null,
        ?string $productionToken = null,
    ): self {
        $self = new self;

        $self['grantType'] = $grantType;

        null !== $clientID && $self['clientID'] = $clientID;
        null !== $clientSecret && $self['clientSecret'] = $clientSecret;
        null !== $code && $self['code'] = $code;
        null !== $productionToken && $self['productionToken'] = $productionToken;

        return $self;
    }

    /**
     * The credential you request in exchange for the code. In Production, this is always `authorization_code`. In Sandbox, you can pass either enum value.
     *
     * @param GrantType|value-of<GrantType> $grantType
     */
    public function withGrantType(GrantType|string $grantType): self
    {
        $self = clone $this;
        $self['grantType'] = $grantType;

        return $self;
    }

    /**
     * The public identifier for your application.
     */
    public function withClientID(string $clientID): self
    {
        $self = clone $this;
        $self['clientID'] = $clientID;

        return $self;
    }

    /**
     * The secret that confirms you own the application. This is redundant given that the request is made with your API key but it's a required component of OAuth 2.0.
     */
    public function withClientSecret(string $clientSecret): self
    {
        $self = clone $this;
        $self['clientSecret'] = $clientSecret;

        return $self;
    }

    /**
     * The authorization code generated by the user and given to you as a query parameter.
     */
    public function withCode(string $code): self
    {
        $self = clone $this;
        $self['code'] = $code;

        return $self;
    }

    /**
     * The production token you want to exchange for a sandbox token. This is only available in Sandbox. Set `grant_type` to `production_token` to use this parameter.
     */
    public function withProductionToken(string $productionToken): self
    {
        $self = clone $this;
        $self['productionToken'] = $productionToken;

        return $self;
    }
}
